name: anonymous_social
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  uuid: ^4.4.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.1 # Added flutter_riverpod

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
